version: '3.9'

networks:
  appnet:


volumes:
  db-data:


services:
  app:
    image: fwszs/react-app:1.0.0
    networks:
      - appnet
    depends_on:
      - api
    ports:
      - 3000:3000
  db:
    image: postgres:12.16-bullseye
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - appnet
    environment:
      - POSTGRES_USER=reactappuser
      - POSTGRES_PASSWORD=somepassword
      - POSTGRES_DB=instantmessage
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
        ]
      interval: 5s
      retries: 15
  api:
    image: fwszs/node-api:1.0.0
    ports:
      - 4000:4000
    networks:
      - appnet
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_NAME=instantmessage
      - DB_USER=reactappuser
      - DB_PASSWORD=somepassword
  websocket:
    image: fwszs/websocket:1.0.0
    ports:
      - 3001:3001
    networks:
      - appnet
    depends_on:
      - api
